### ISSUE TITLE
Support for windows: Language files fail to load due to differences in path systems

### ISSUE THREAD

**Issue by hhakuri** [TeamKun/Scenamatica#1]
## Summary
For windows environment, language files fail to load due to differences in path systems.

Scenamatica 本体ではなく依存している [PeyangPaperUtils](https://github.com/TeamKun/PeyangPaperUtils) が windows 環境だと正常に動作せずエラーとなっているようです。
せっかくなので windows 環境でテストコードを書きたく、Issue を切りました。Win 使っている情弱でスミマセン。

https://github.com/TeamKun/PeyangPaperUtils/blob/2b170f3592bed0fbb515d754d25b6a6bd5dbd60e/src/main/java/net/kunmc/lab/peyangpaperutils/lang/LangLoader.java#L136C2-L161
の
https://github.com/TeamKun/PeyangPaperUtils/blob/2b170f3592bed0fbb515d754d25b6a6bd5dbd60e/src/main/java/net/kunmc/lab/peyangpaperutils/lang/LangLoader.java#L139
の行でパスの文字列を取得していますが、win 環境では `lang¥ja_JP` となり、
https://github.com/TeamKun/PeyangPaperUtils/blob/2b170f3592bed0fbb515d754d25b6a6bd5dbd60e/src/main/java/net/kunmc/lab/peyangpaperutils/lang/LangLoader.java#L149
で得られる key は `lang/ja_JP.lang` なのでディレクトリの区切り文字が違いマッチしなくなると思われます。

## Errors

```
[02:37:37 INFO]: [Scenamatica] Enabling Scenamatica v0.7.0
[02:37:37 INFO]: [Scenamatica] Found 3 language files in the jar file.
[02:37:39 ERROR]: Error occurred while enabling Scenamatica v0.7.0 (Is it up to date?)
java.lang.IllegalStateException: Language file "ja_JP" not found in the jar file.
	at net.kunmc.lab.scenamatica.pyglib.lang.LangLoader.loadLanguageFromJar(LangLoader.java:157) ~[?:?]
	at net.kunmc.lab.scenamatica.pyglib.lang.LangLoader.loadLanguage(LangLoader.java:131) ~[?:?]
	at net.kunmc.lab.scenamatica.pyglib.lang.LangProvider.setLanguage(LangProvider.java:93) ~[?:?]
	at net.kunmc.lab.scenamatica.Scenamatica.initLangProvider(Scenamatica.java:124) ~[?:?]
	at net.kunmc.lab.scenamatica.Scenamatica.onEnable(Scenamatica.java:63) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:270) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

## System configuration
MC version: 1.16.5-R0.1-SNAPSHOT
Scenamatica version: v0.7.0

**Comment by hhakuri** [comment]
手軽な修正は
https://github.com/TeamKun/PeyangPaperUtils/blob/2b170f3592bed0fbb515d754d25b6a6bd5dbd60e/src/main/java/net/kunmc/lab/peyangpaperutils/lang/LangLoader.java#L149
```
String entryName = Paths.get(entry.getName()).toString();
```
とするなどですかね…。

**Comment by PeyaPeyaPeyang** [comment]
Issue ありがとうございます。(；´∀｀)
問題を当該環境で再現, および修正確認ができました。

ご指摘の通り, パスの区切り文字がWindows 環境下ではバックスラッシュ(`\`) なことに起因するバグでした。
[PeyangPaperUtils@v2.2.1](https://github.com/TeamKun/PeyangPaperUtils/releases/tag/2.2.1) で修正いたしました。

Scenamatica の修正バージョンは, 他の変更を含めておおよそ３日以内を目処にリリースいたします～
